name: Release Creation

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: audit
      - uses: actions/checkout@v3.3.0
      - uses: teaxyz/setup@v0
      - name: Build Windows
        run: tea xc build:windows
      - name: Build Linux
        run: tea xc build:linux
      - name: Build MacOS x86
        run: tea xc build:macos86
      - name: Build MacOS aarch64
        run: tea xc build:macos
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1.12.0
        with:
            allowUpdates: true # Set this to false if you want to prevent updating existing releases
            name: ${{ github.event.release.name }}
            draft: ${{ github.event.release.unpublished }}
            prerelease: ${{ github.event.release.prerelease }}
            token: ${{ secrets.GITHUB_TOKEN }}
            artifacts: './server-linux, ./server.exe, ./server-macos-aarch64, ./server-macos-x86'
            tag: ${{ github.event.release.tag_name }}
            body: ${{ github.event.release.body }}